[target.aarch64-apple-darwin]
rustflags = ["-l", "framework=Accelerate"]

[target.x86_64-apple-darwin]
rustflags = ["-l", "framework=Accelerate"]

[package.metadata.darwin]
frameworks = ["AppKit", "LaunchServices"]
